const fakeUsers = [
  {
    id: 1,
    image: 'https://robohash.org/hicveldicta.png',
    firstName: 'Terry',
    lastName: 'Medhurst',
    birthDate: '2000-12-25',
    department: 'Marketing',
  },
  {
    id: 2,
    image: 'https://robohash.org/doloremquesintcorrupti.png',
    firstName: 'Sheldon',
    lastName: 'Quigley',
    birthDate: '2003-08-02',
    department: 'Services',
  },
  {
    id: 3,
    image: 'https://robohash.org/consequunturautconsequatur.png',
    firstName: 'Terrill',
    lastName: 'Hills',
    birthDate: '1992-12-30',
    department: 'Marketing',
  },
  {
    id: 4,
    image: 'https://robohash.org/facilisdignissimosdolore.png',
    firstName: 'Miles',
    lastName: 'Cummerata',
    birthDate: '1969-01-16',
    department: 'Business Development',
  },
  {
    id: 5,
    image: 'https://robohash.org/adverovelit.png',
    firstName: 'Mavis',
    lastName: 'Schultz',
    birthDate: '1968-11-03',
    department: 'Support',
  },
  {
    id: 6,
    image: 'https://robohash.org/laboriosamfacilisrem.png',
    firstName: 'Alison',
    lastName: 'Reichert',
    birthDate: '1969-07-21',
    department: 'Accounting',
  },
  {
    id: 7,
    image: 'https://robohash.org/cupiditatererumquos.png',
    firstName: 'Oleta',
    lastName: 'Abbott',
    birthDate: '1982-02-21',
    department: 'Product Management',
  },
  {
    id: 8,
    image: 'https://robohash.org/quiaharumsapiente.png',
    firstName: 'Ewell',
    lastName: 'Mueller',
    birthDate: '1964-08-24',
    department: 'Services',
  },
  {
    id: 9,
    image: 'https://robohash.org/excepturiiuremolestiae.png',
    firstName: 'Demetrius',
    lastName: 'Corkery',
    birthDate: '1971-03-11',
    department: 'Human Resources',
  },
  {
    id: 10,
    image: 'https://robohash.org/aliquamcumqueiure.png',
    firstName: 'Eleanora',
    lastName: 'Price',
    birthDate: '1958-08-11',
    department: 'Marketing',
  },
  {
    id: 11,
    image: 'https://robohash.org/impeditautest.png',
    firstName: 'Marcel',
    lastName: 'Jones',
    birthDate: '1961-09-12',
    department: 'Business Development',
  },
  {
    id: 12,
    image: 'https://robohash.org/namquaerataut.png',
    firstName: 'Assunta',
    lastName: 'Rath',
    birthDate: '1990-12-14',
    department: 'Product Management',
  },
  {
    id: 13,
    image: 'https://robohash.org/voluptatemsintnulla.png',
    firstName: 'Trace',
    lastName: 'Douglas',
    birthDate: '1967-07-23',
    department: 'Research and Development',
  },
  {
    id: 14,
    image: 'https://robohash.org/quisequienim.png',
    firstName: 'Enoch',
    lastName: 'Lynch',
    birthDate: '1979-08-25',
    department: 'Sales',
  },
  {
    id: 15,
    image: 'https://robohash.org/autquiaut.png',
    firstName: 'Jeanne',
    lastName: 'Halvorson',
    birthDate: '1996-02-02',
    department: 'Marketing',
  },
  {
    id: 16,
    image: 'https://robohash.org/porronumquamid.png',
    firstName: 'Trycia',
    lastName: 'Fadel',
    birthDate: '1963-07-03',
    department: 'Research and Development',
  },
  {
    id: 17,
    image: 'https://robohash.org/accusantiumvoluptateseos.png',
    firstName: 'Bradford',
    lastName: 'Prohaska',
    birthDate: '1975-10-20',
    department: 'Sales',
  },
  {
    id: 18,
    image: 'https://robohash.org/nihilharumqui.png',
    firstName: 'Arely',
    lastName: 'Skiles',
    birthDate: '1958-02-05',
    department: 'Support',
  },
  {
    id: 19,
    image: 'https://robohash.org/delenitipraesentiumvoluptatum.png',
    firstName: 'Gust',
    lastName: 'Purdy',
    birthDate: '1989-10-15',
    department: 'Sales',
  },
  {
    id: 20,
    image: 'https://robohash.org/ipsumutofficiis.png',
    firstName: 'Lenna',
    lastName: 'Renner',
    birthDate: '1980-01-19',
    department: 'Support',
  },
  {
    id: 21,
    image: 'https://robohash.org/providenttemporadelectus.png',
    firstName: 'Doyle',
    lastName: 'Ernser',
    birthDate: '1983-01-22',
    department: 'Product Management',
  },
  {
    id: 22,
    image: 'https://robohash.org/temporarecusandaeest.png',
    firstName: 'Tressa',
    lastName: 'Weber',
    birthDate: '1987-11-11',
    department: 'Research and Development',
  },
  {
    id: 23,
    image: 'https://robohash.org/odioquivero.png',
    firstName: 'Felicity',
    lastName: "O'Reilly",
    birthDate: '1967-10-05',
    department: 'Legal',
  },
  {
    id: 24,
    image: 'https://robohash.org/odiomolestiaealias.png',
    firstName: 'Jocelyn',
    lastName: 'Schuster',
    birthDate: '1966-06-02',
    department: 'Product Management',
  },
  {
    id: 25,
    image: 'https://robohash.org/doloremautdolores.png',
    firstName: 'Edwina',
    lastName: 'Ernser',
    birthDate: '2000-09-28',
    department: 'Marketing',
  },
  {
    id: 26,
    image: 'https://robohash.org/laboriosammollitiaut.png',
    firstName: 'Griffin',
    lastName: 'Braun',
    birthDate: '1965-09-06',
    department: 'Engineering',
  },
  {
    id: 27,
    image: 'https://robohash.org/nequeodiosapiente.png',
    firstName: 'Piper',
    lastName: 'Schowalter',
    birthDate: '1983-06-07',
    department: 'Human Resources',
  },
  {
    id: 28,
    image: 'https://robohash.org/consequunturabnon.png',
    firstName: 'Kody',
    lastName: 'Terry',
    birthDate: '1979-01-09',
    department: 'Support',
  },
  {
    id: 29,
    image: 'https://robohash.org/amettemporeea.png',
    firstName: 'Macy',
    lastName: 'Greenfelder',
    birthDate: '1976-09-07',
    department: 'Product Management',
  },
  {
    id: 30,
    image: 'https://robohash.org/perferendisideveniet.png',
    firstName: 'Maurine',
    lastName: 'Stracke',
    birthDate: '1964-12-18',
    department: 'Support',
  },
];

export default fakeUsers;
